### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by bruvv** [NNScripts/nn-custom-scripts#3]
```
DEBUG: Release [Frozen.Planet.2011.E01.To.the.Ends.of.the.Earth.720p.BluRay.x264-EbP] does matches blacklist regex:
DEBUG: Regex (100025): nintendo|wii|ps3|xbox|nds|psp
DEBUG: Matches: nds
```

```
DEBUG: Release [00-deportees-islands_and_shores-(eko150)-cd-2011-gcp] does matches blacklist regex:
DEBUG: Regex (100025): nintendo|wii|ps3|xbox|nds|psp
DEBUG: Matches: nds
```

```
DEBUG: Release [Gone.In.Sixty.Seconds.2000.720p.BRRip.x264-Rx] does matches blacklist regex:
DEBUG: Regex (100025): nintendo|wii|ps3|xbox|nds|psp
DEBUG: Matches: nds
```

(and alot more)
Is this your script that is matching it, or is the regex not right?

**Comment by NNScripts** [comment]
The matches are false positives because the regex does allow to much (not strict enough).
The script just checks the active black/white regexes, and if matched (or not matched in case of a whitelist) it can remove the releases.

The regex "nintendo|wii|ps3|xbox|nds|psp" wil match if one (or more) of the strings are found in the release title
Words like "Ends", "islands" and "Seconds" all contain the string "nds" which is part if the regex.

It would be better to check for a separator (dot, space, underscore) before the words like so:

<pre>[\s_\.-](nintendo|wii|ps3|xbox|nds|psp)</pre>

Sadly enough I cannot prevent this from happening in the code (and this will also happen during the update process). If the regex is not strict enough it always have false positives (although I don't think false positives can be prevented completely). The looser the regex, the more false positives there are.

[update].
Due to these loose regexes all these words will also match the "nds" part:
http://itools.subhashbose.com/wordfind/ending-with/nds

**Comment by bruvv** [comment]
Nice thanks a lot I will add these to the blacklist now ;)
